# Generated by Django 4.2 on 2024-02-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("sales_channel", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("single", "Single"), ("bundle", "Bundle")],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "bundled_products",
                    models.ManyToManyField(
                        blank=True, related_name="bundles", to="e_commerce.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="e_commerce.product",
                    ),
                ),
            ],
        ),
    ]
