# Generated by Django 4.2 on 2024-02-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="e_commerce.productstock",
            ),
        ),
    ]
