# Generated by Django 4.2 on 2024-02-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleproduct",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products_%(class)s_related",
                to="e_commerce.product",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="e_commerce.product"
            ),
        ),
    ]
