# Generated by Django 4.2 on 2024-02-14 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0002_alter_bundleproduct_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="catalog",
            name="stock_id",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="product",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 2, 14, 17, 39, 19, 806578, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("Single", "Single"), ("Bundle", "Bundle")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Stock Count"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Product Name"),
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.DeleteModel(
            name="BundleProduct",
        ),
        migrations.DeleteModel(
            name="Catalog",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
