# Generated by Django 4.2 on 2024-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "e_commerce",
            "0003_remove_catalog_product_id_remove_catalog_stock_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Stock Count"
            ),
        ),
    ]
