# Generated by Django 4.2 on 2024-02-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0005_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
