# Generated by Django 4.2 on 2024-02-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0006_remove_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Stock Count"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_count",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="e_commerce.productstock",
            ),
        ),
    ]
