# Generated by Django 4.2 on 2024-02-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0011_alter_product_stock_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_count",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="e_commerce.productstock",
            ),
        ),
    ]
