# Generated by Django 4.2 on 2024-02-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_commerce", "0012_alter_product_stock_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock_count",
            new_name="stock",
        ),
    ]
